export const MODULES = [
    {
        id: 'dashboard',
        name: 'Dashboard',
        headline: 'Your property at a glance',
        description: 'Real-time occupancy, revenue, today\'s arrivals/departures, pending tasks, quick actions — all on one screen.',
        icon: '📊',
        color: '#e94560',
    },
    {
        id: 'bookings',
        name: 'Bookings',
        headline: 'Every booking, one place',
        description: 'Create, manage, modify bookings. Multi-source (direct, OTA, walk-in). Calendar and list views. Partial payments, status tracking.',
        icon: '📅',
        color: '#9b5de5',
    },
    {
        id: 'rooms',
        name: 'Rooms',
        headline: 'Room control center',
        description: 'Room categories, individual room status, drag-and-drop assignment, floor plan view. Live housekeeping status.',
        icon: '🛏️',
        color: '#06d6a0',
    },
    {
        id: 'housekeeping',
        name: 'Housekeeping',
        headline: 'Clean rooms, happy guests',
        description: 'Cleaning queue, assignment, checklists, completion tracking, performance metrics per housekeeper.',
        icon: '🧹',
        color: '#f77f00',
    },
    {
        id: 'guests',
        name: 'Guests',
        headline: 'Know your guests',
        description: 'Guest profiles, stay history, ID verification, preferences, communication log, guest reviews received.',
        icon: '👤',
        color: '#00b4d8',
    },
    {
        id: 'staff',
        name: 'Staff & Roles',
        headline: 'Right access, right people',
        description: 'Invite staff, assign per-property roles (Manager, Front Desk, Housekeeping, Custom), granular permissions.',
        icon: '👥',
        color: '#ffd60a',
    },
    {
        id: 'billing',
        name: 'Billing & Payments',
        headline: 'Every rupee tracked',
        description: 'Multi-payment tracking (cash, UPI, card, online), split bills, receipt generation, daily collection reports.',
        icon: '💳',
        color: '#e94560',
    },
    {
        id: 'channels',
        name: 'Channel Manager',
        headline: 'Sync once, sell everywhere',
        description: 'Connect Airbnb, Booking.com, MakeMyTrip. Auto-sync availability, rates, and bookings in real-time.',
        icon: '🔄',
        color: '#9b5de5',
    },
    {
        id: 'inventory',
        name: 'Inventory',
        headline: 'Track, sell, restock',
        description: 'Minibar, food, supplies — cost & selling price, stock tracking, sell to guests (auto-adds to booking bill), low-stock alerts.',
        icon: '📦',
        color: '#06d6a0',
    },
    {
        id: 'reviews',
        name: 'Reviews',
        headline: 'Two-way reputation',
        description: 'Guests review your property (6 sub-ratings). You review guests (cleanliness, rules, respect). Public responses.',
        icon: '⭐',
        color: '#ffd60a',
    },
    {
        id: 'messaging',
        name: 'Messaging',
        headline: 'All conversations, one inbox',
        description: 'In-app chat, Airbnb messages, WhatsApp — unified. Internal staff notes. Auto-replies.',
        icon: '💬',
        color: '#00b4d8',
    },
    {
        id: 'website-builder',
        name: 'Website Builder',
        headline: "Your property's website",
        description: 'Custom domain or subdomain. Templates, themes, booking widget. SEO ready. No code needed.',
        icon: '🌐',
        color: '#f77f00',
    },
    {
        id: 'reports',
        name: 'Reports & Analytics',
        headline: 'Data-driven decisions',
        description: 'Revenue, occupancy, ADR, RevPAR, source-wise breakdown, expense tracking, P&L reports.',
        icon: '📈',
        color: '#e94560',
    },
];

export const PROPERTY_TYPES = [
    { label: 'Homestay', emoji: '🏡' },
    { label: 'Hotel', emoji: '🏨' },
    { label: 'Resort', emoji: '🏖️' },
    { label: 'Villa', emoji: '🏠' },
    { label: 'Apartment', emoji: '🏢' },
    { label: 'Hostel', emoji: '🛏️' },
    { label: 'Guest House', emoji: '🏘️' },
];
