/** Kept in sync with the `name` union in `src/components/Icon.astro` by hand — small, stable set. */
export type IconName =
  | 'search'
  | 'map-pin'
  | 'chat'
  | 'mic'
  | 'receipt'
  | 'calendar'
  | 'shield-check'
  | 'users'
  | 'list'
  | 'globe'
  | 'phone'
  | 'mail'
  | 'check'
  | 'x'
  | 'arrow-right'
  | 'wallet'
  | 'building'
  | 'palette'
  | 'layout'
  | 'key'
  | 'bell'
  | 'sparkle';
